Arrays
AndrejDurasow/study pull request #1
Opened 2020-04-24 08:57 UTC by AndrejDurasow

2020-04-24 14:39 UTC, Andrew8xx8 requested changes

2020-04-24 14:39 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        array.map { |i| i > 0 ? array.max : i }
Нужно самому реализовать `max`

2020-04-24 14:39 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        mini = 0
Не могу понять название `mini` и `maxi`? мини и макси что? 

Это похожу на левый и правый индексы, следует назвать переменные так, каким является их смысл

2020-04-24 15:31 UTC, AndrejDurasow commented on test/exercise/arrays/solution.rb
> +        array.map { |i| i > 0 ? array.max : i }
исправил

2020-04-24 15:32 UTC, AndrejDurasow commented on test/exercise/arrays/solution.rb
> +        mini = 0
да, это первый и последний элемент массива. исправил.

2020-04-25 18:58 UTC, Andrew8xx8 approved these changes

2020-04-30 11:53 UTC, merged