Fp
AndrejDurasow/study pull request #2
Opened 2020-04-26 19:11 UTC by AndrejDurasow

2020-04-27 17:25 UTC, mkalmykov requested changes

2020-04-27 17:25 UTC, mkalmykov commented on .gitignore
> +.DS_Store
Хорошей практикой считается добавлять в гитигнор только файлы, относящиеся к проекту. `.DS_Store` является файлом, специфичным для ОС разработчика, и обычно такие файлы добавляются в глобальный гитигнор, который находится в домашней директории.

2020-04-27 17:25 UTC, mkalmykov commented on test/exercise/arrays/solution.rb
> +        array.map { |i| i > 0 ? array.max : i }
Нужно реализовать метод `max` самостоятельно.

2020-04-27 17:25 UTC, mkalmykov commented on test/exercise/arrays/solution.rb
> +      def search(array, query)
Попробуй реализовать этот метод рекурсивно.

2020-04-27 17:25 UTC, mkalmykov commented on test/exercise/fp/solution.rb
> +        reit = array.filter_map { |film| film if film["country"].present? }.
`reit` -- не очень хорошее название для переменной по нескольким причинам:

1. Чаще всего сокращение имен переменных -- это экономия на спичках, потому что современные компьютеры достаточно производительны, плюс среды выполнения могут сами оптимизировать код. Лучше ставить на первое место читаемость.
2. Сокращение `reit` некорректно с точки зрения английского языка.

2020-04-27 17:25 UTC, mkalmykov commented on test/exercise/fp/solution.rb
> +                     filter_map { |film| film["rating_kinopoisk"].to_f if film["country"].split(',').length >= 2 }
Можно ли сократить количество проходов по массиву?

2020-04-27 17:25 UTC, mkalmykov commented on test/exercise/fp/solution.rb
> +        res = films.filter_map { |film| film unless film["rating_kinopoisk"].nil? }.
Обычно условные конструкции с `if` более читабельны. Здесь можно инвертировать условие, применив предикат `.present?` вместо `.nil?`.

2020-04-27 19:42 UTC, AndrejDurasow commented on .gitignore
> +.DS_Store
с этим файлом история интересная была, я в слаке задавал вопрос у меня pr не создавался, оказалось что несколько репозиториев .git было в корне, с Ильей Шакировым созванивались в зуме, решали эту проблему и дописывали эту строку в гитигнор... че мне исправить?)

2020-04-28 07:43 UTC, mkalmykov commented on .gitignore
> +.DS_Store
В глобальном конфиге гита (`git config --global -e`), в секции `[core]` должен быть указан глобальный excludesfile. Выглядит примерно так:

```
[core]
          excludesfile = ~/.gitignore
```

Если такого файла в домашней директории нет -- надо создать и перенести `.DS_Store` туда.

2020-04-28 07:58 UTC, AndrejDurasow commented on .gitignore
> +.DS_Store
ну в консоли набрал команду, в блоке core нет такой строки excludesfile = ~/.gitignore. в домашней директории в гитигнор есть строка .DS_Store...

2020-04-28 07:59 UTC, mkalmykov commented on .gitignore
> +.DS_Store
Вот как раз надо добавить эту строку в конфиг.

2020-04-28 08:00 UTC, AndrejDurasow commented on .gitignore
> +.DS_Store
ага, понял) щас сделаем.

2020-04-29 09:05 UTC, AndrejDurasow commented on test/exercise/fp/solution.rb
> +        res = films.filter_map { |film| film unless film["rating_kinopoisk"].nil? }.
исправил.

2020-04-29 09:07 UTC, AndrejDurasow commented on test/exercise/fp/solution.rb
> +                     filter_map { |film| film["rating_kinopoisk"].to_f if film["country"].split(',').length >= 2 }
пробовал несколько условий писать в одну строчку через && , тесты ошибку выдают.. не знаю как сократить...

2020-04-29 09:07 UTC, AndrejDurasow commented on test/exercise/fp/solution.rb
> +        reit = array.filter_map { |film| film if film["country"].present? }.
исправил

2020-04-29 11:36 UTC, Andrew8xx8 requested changes

2020-04-29 11:36 UTC, Andrew8xx8 commented on test/exercise/fp/solution.rb
> +                     filter_map { |film| film["rating_kinopoisk"].to_f if film["country"].split(',').length >= 2 }
Так как код мы не видим, мы не можем сказать в чем у тебя ошибка была.

Попробуй еще раз переписать, используй select и map отдельно

2020-04-29 11:36 UTC, Andrew8xx8 commented
Из этого PR нужно убрать коммиты от предыдущего задания

2020-05-07 07:25 UTC, mkalmykov requested changes

2020-05-07 07:25 UTC, mkalmykov commented on test/exercise/fp/solution.rb
> +        rate = array.select { |film| film['country'].to_s.include?(',') &&
Попробуй вместо приведения country к строке сначала отсечь nil'ы.

2020-05-07 07:25 UTC, mkalmykov commented on test/exercise/fp/solution.rb
> +      def rating(array)
Отформатируй файл рубокопом.

2020-05-07 07:25 UTC, mkalmykov commented on test/exercise/rackup/my_app.rb
> +  get '/ping' do
Всё, что относится к веб-фреймворку, нужно перенести в PR про веб-фреймворк.

2020-05-07 10:20 UTC, AndrejDurasow commented on test/exercise/rackup/my_app.rb
> +  get '/ping' do
не пойму как отсюда убрать... когда смотрю гит хист в этой ветке там ничего кроме относящихся к фп нет... делаю гит пуш -f , но файл из фреймворка все равно присутствует

2020-05-14 12:43 UTC, Andrew8xx8 approved these changes

2020-05-15 12:49 UTC, merged