fp2
AndrejDurasow/study pull request #3
Opened 2020-04-26 20:09 UTC by AndrejDurasow

2020-04-27 17:27 UTC, mkalmykov requested changes

2020-04-27 17:27 UTC, mkalmykov commented on test/exercise/fp/test.rb
> -    skip
Решения тоже должны быть в этом PR. Нужно перенести их из https://github.com/AndrejDurasow/study/pull/2 сюда.

2020-04-29 09:16 UTC, AndrejDurasow commented on test/exercise/fp/test.rb
> -    skip
блин, я вроде в ветке fp2 все делал... мне щас запушить заново из ветки fp2 сюда в ориджин надо?

2020-04-29 11:37 UTC, Andrew8xx8 requested changes

2020-04-29 11:37 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        self.my_each { |el| res << yield(el)}
Нужно реализовать через reduce

2020-04-29 11:37 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        self.my_each { |el| res << el unless el.nil? }
Нужно реализовать через reduce

2020-04-29 11:37 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        self.my_each { |el| res = res.nil? ? el : yield(res, el) }
Нужно реализовать используя рекурсивный итератор

2020-04-30 13:24 UTC, AndrejDurasow commented on test/exercise/fp2/solution.rb
> +        self.my_each { |el| res << yield(el)}
исправил

2020-04-30 13:24 UTC, AndrejDurasow commented on test/exercise/fp2/solution.rb
> +        self.my_each { |el| res << el unless el.nil? }
исправил

2020-04-30 13:24 UTC, AndrejDurasow commented on test/exercise/fp2/solution.rb
> +        self.my_each { |el| res = res.nil? ? el : yield(res, el) }
исправил

2020-05-07 07:21 UTC, mkalmykov requested changes

2020-05-07 07:21 UTC, mkalmykov commented on test/exercise/fp2/solution.rb
> +        for el in self
Цикл for в Ruby обычно не применяют, потому что он не создаёт область видимости. Попробуй использовать другой цикл.

2020-05-07 07:21 UTC, mkalmykov commented on test/exercise/fp2/solution.rb
> +          unless el.nil?
Это условие можно написать в одну строку.

2020-05-14 12:44 UTC, Andrew8xx8 approved these changes

2020-05-15 12:50 UTC, merged