Rackup
AndrejDurasow/study pull request #4
Opened 2020-04-27 11:25 UTC by AndrejDurasow

2020-04-27 17:33 UTC, mkalmykov requested changes

2020-04-27 17:33 UTC, mkalmykov commented on .gitignore
> +.DS_Store
Тот же комментарий здесь: https://github.com/AndrejDurasow/study/pull/2#discussion_r415999952

2020-04-27 17:33 UTC, mkalmykov commented on test/exercise/arrays/solution.rb
> +      def search(array, query)
Решение этой задачи должно быть в другой ветке.

2020-04-27 17:33 UTC, mkalmykov commented on test/exercise/fp/solution.rb
> +      def rating(array)
Решение этой задачи должно быть в другой ветке.

2020-04-27 17:33 UTC, mkalmykov commented on test/exercise/rackup/inatra.rb
> +      @route = {}
Нужно подобрать другое название. Во-первых в хеше хранится много элементов, поэтому оно не должно быть в единственном числе, во-вторых там лежат не маршруты, и `route` тут не подходит по смыслу.

2020-04-27 17:33 UTC, mkalmykov commented on test/exercise/rackup/inatra.rb
> +      method = env['REQUEST_METHOD'].to_s.downcase
Нужно ли дополнительно вызывать `to_s`?

2020-04-27 17:33 UTC, mkalmykov commented on test/exercise/rackup/inatra.rb
> +    def method_missing(method_name, *arg, &block)
Распаковка `*arg` подразумевает, что аргументов там может быть много, поэтому единственное число не подходит для названия.

2020-04-27 17:33 UTC, mkalmykov commented on test/exercise/rackup/inatra.rb
> +      @route[method] = {}
Добавь ещё один get-роут в my_app.rb и тест на него.

2020-04-28 10:53 UTC, AndrejDurasow commented on test/exercise/rackup/inatra.rb
> +      @route = {}
у меня с английским туговато, поэтому назвал как и метод только в единственном числе)

2020-05-07 07:26 UTC, mkalmykov commented
В этом PR должны быть только те изменения, которые относятся к заданию про веб-фреймворк.

2020-05-14 12:44 UTC, Andrew8xx8 approved these changes

2020-05-15 12:50 UTC, merged